#!/usr/bin/env python3
#	dspbptk - Dyson Sphere Program Blueprint Toolkit
#	Copyright (C) 2021-2022 Johannes Bauer
#
#	This file is part of dspbptk.
#
#	dspbptk is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	dspbptk is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys
from MultiCommand import MultiCommand
from ActionBlueprintToJSON import ActionBlueprintToJSON
from ActionJSONToBlueprint import ActionJSONToBlueprint
from ActionDump import ActionDump
from ActionEdit import ActionEdit
from ActionSearchUnknownIds import ActionSearchUnknownIds
from ActionInspect import ActionInspect
from ActionValidateSerialize import ActionValidateSerialize
from ActionAnnotate import ActionAnnotate
from ActionReplace import ActionReplace

mc = MultiCommand()

ActionBlueprintToJSON.register(mc)
ActionDump.register(mc)
ActionJSONToBlueprint.register(mc)
ActionEdit.register(mc)
ActionSearchUnknownIds.register(mc)
ActionInspect.register(mc)
ActionValidateSerialize.register(mc)
ActionAnnotate.register(mc)
ActionReplace.register(mc)

mc.run(sys.argv[1:])
